AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'client/node_modules/**/*'
    - 'bin/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 80

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
